defaults:
  - covariates: agesex
  - sampler: dummy_sampler
  - _self_

batch_size: 8192
partition: 0
num_workers: 4

label_definition:
  all_cause_death: True
  phecodes: True
  custom: []
t0_mode: recruitment
use_top_n_phecodes: 1000
edge_weight_threshold: 0.1
min_edge_type_fraction: 0.001
buffer_years: 0.
filter_input_origins: []
use_phecode_inputs: True
use_specific_records: null
load_embeddings_path: null
use_loss_weights: False
